from scipy import linalg
import numpy as np

a = np.array([1, 2, 3]) 
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức 
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) ) 
B = np.asmatrix(b) 
C = np.mat(np.random.random( (10,5) ) ) 
D = np.mat([ [4, 3], [2, 6] ]) 
F = np.eye(3, k=1)
print(F)
F = np.eye(3, k=0) 
print(F)
F = np.eye(3, k=-1)
print(F)
print(np.linalg.matrix_rank(C))
print(A.I)
print(linalg.inv(A))
print(linalg.det(A))
print(A.T)
print(A.H)
print(linalg.solve(A, b))
E = np.mat(a).T
print(E)
print(linalg.lstsq(F, E))
print(np.add(A, D))
print(np.subtract(A, D))
print(np.divide(A, D))
print( A @ D )
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.vdot(A, D))
print(linalg.expm(A))
print(linalg.logm(A))